package com.inspiredandroid.kai.ui.settings

import androidx.compose.runtime.Immutable
import com.inspiredandroid.kai.data.ImportSection
import com.inspiredandroid.kai.data.Service
import com.inspiredandroid.kai.inference.LocalModel
import com.inspiredandroid.kai.mcp.PopularMcpServer

@Immutable
data class SettingsActions(
    val onSelectTab: (SettingsTab) -> Unit,
    val onAddService: (Service) -> Unit,
    val onRemoveService: (String) -> Unit,
    val onReorderServices: (List<String>) -> Unit,
    val onExpandService: (String?) -> Unit,
    val onChangeApiKey: (String, String) -> Unit,
    val onChangeBaseUrl: (String, String) -> Unit,
    val onSelectModel: (String, String) -> Unit,
    val onToggleTool: (String, Boolean) -> Unit,
    val onSaveSoul: (String) -> Unit,
    val onToggleDynamicUi: (Boolean) -> Unit,
    val onToggleOledMode: (Boolean) -> Unit,
    val onToggleMemory: (Boolean) -> Unit,
    val onDeleteMemory: (String) -> Unit,
    val onUpdateMemory: (String, String) -> Unit,
    val onToggleScheduling: (Boolean) -> Unit,
    val onCancelTask: (String) -> Unit,
    val onToggleDaemon: (Boolean) -> Unit,
    val onToggleHeartbeat: (Boolean) -> Unit,
    val onChangeHeartbeatInterval: (Int) -> Unit,
    val onChangeHeartbeatActiveHours: (Int, Int) -> Unit,
    val onSaveHeartbeatPrompt: (String) -> Unit,
    val onChangeHeartbeatService: (String?) -> Unit,
    val onRefreshHeartbeat: () -> Unit,
    val onToggleEmail: (Boolean) -> Unit,
    val onRemoveEmailAccount: (String) -> Unit,
    val onChangeEmailPollInterval: (Int) -> Unit,
    val onRefreshEmailAccount: (String) -> Unit,
    val onToggleSms: (Boolean) -> Unit,
    val onChangeSmsPollInterval: (Int) -> Unit,
    val onRefreshSms: () -> Unit,
    val onToggleSmsSend: (Boolean) -> Unit,
    val onToggleFreeFallback: (Boolean) -> Unit,
    val onChangeUiScale: (Float) -> Unit,
    val onAddMcpServer: (String, String, Map<String, String>) -> Unit,
    val onRemoveMcpServer: (String) -> Unit,
    val onToggleMcpServer: (String, Boolean) -> Unit,
    val onRefreshMcpServer: (String) -> Unit,
    val onShowAddMcpServerDialog: (Boolean) -> Unit,
    val onAddPopularMcpServer: (PopularMcpServer) -> Unit,
    val onDownloadLocalModel: (LocalModel) -> Unit,
    val onCancelLocalModelDownload: () -> Unit,
    val onDeleteLocalModel: (String) -> Unit,
    val onChangeModelContextTokens: (String, Int) -> Unit,
    val onExportSettings: (Set<ImportSection>) -> String,
    val onPrepareExport: () -> Map<ImportSection, String?>,
    val onImportSettings: (ByteArray, Set<ImportSection>, Boolean) -> ImportResult,
    val onUndoDelete: () -> Unit,
) {
    companion object {
        val NoOp = SettingsActions(
            onSelectTab = {},
            onAddService = {},
            onRemoveService = {},
            onReorderServices = {},
            onExpandService = {},
            onChangeApiKey = { _, _ -> },
            onChangeBaseUrl = { _, _ -> },
            onSelectModel = { _, _ -> },
            onToggleTool = { _, _ -> },
            onSaveSoul = {},
            onToggleDynamicUi = {},
            onToggleOledMode = {},
            onToggleMemory = {},
            onDeleteMemory = {},
            onUpdateMemory = { _, _ -> },
            onToggleScheduling = {},
            onCancelTask = {},
            onToggleDaemon = {},
            onToggleHeartbeat = {},
            onChangeHeartbeatInterval = {},
            onChangeHeartbeatActiveHours = { _, _ -> },
            onSaveHeartbeatPrompt = {},
            onChangeHeartbeatService = {},
            onRefreshHeartbeat = {},
            onToggleEmail = {},
            onRemoveEmailAccount = {},
            onChangeEmailPollInterval = {},
            onRefreshEmailAccount = {},
            onToggleSms = {},
            onChangeSmsPollInterval = {},
            onRefreshSms = {},
            onToggleSmsSend = {},
            onToggleFreeFallback = {},
            onChangeUiScale = {},
            onAddMcpServer = { _, _, _ -> },
            onRemoveMcpServer = {},
            onToggleMcpServer = { _, _ -> },
            onRefreshMcpServer = {},
            onShowAddMcpServerDialog = {},
            onAddPopularMcpServer = {},
            onDownloadLocalModel = {},
            onCancelLocalModelDownload = {},
            onDeleteLocalModel = {},
            onChangeModelContextTokens = { _, _ -> },
            onExportSettings = { _ -> "" },
            onPrepareExport = { emptyMap() },
            onImportSettings = { _, _, _ -> ImportResult.Failure },
            onUndoDelete = {},
        )
    }
}
