package com.inspiredandroid.kai.ui.markdown

/**
 * GFM-style emoji shortcode map (e.g. `:tada:` → 🎉). Covers the commonly-used subset that
 * LLMs emit in chat responses and README-style docs; unknown shortcodes are left as literal
 * text so they remain visible instead of silently disappearing.
 */
internal val EMOJI_SHORTCODES: Map<String, String> = mapOf(
    // Faces
    "smile" to "\uD83D\uDE04",
    "grin" to "\uD83D\uDE01",
    "joy" to "\uD83D\uDE02",
    "laughing" to "\uD83D\uDE06",
    "wink" to "\uD83D\uDE09",
    "blush" to "\uD83D\uDE0A",
    "thinking" to "\uD83E\uDD14",
    "hugs" to "\uD83E\uDD17",
    "cry" to "\uD83D\uDE22",
    "sob" to "\uD83D\uDE2D",
    "rage" to "\uD83D\uDE21",
    "shrug" to "\uD83E\uDD37",
    "relieved" to "\uD83D\uDE0C",
    "sweat_smile" to "\uD83D\uDE05",
    "unamused" to "\uD83D\uDE12",
    // Hands / body
    "+1" to "\uD83D\uDC4D",
    "-1" to "\uD83D\uDC4E",
    "thumbsup" to "\uD83D\uDC4D",
    "thumbsdown" to "\uD83D\uDC4E",
    "ok_hand" to "\uD83D\uDC4C",
    "clap" to "\uD83D\uDC4F",
    "muscle" to "\uD83D\uDCAA",
    "pray" to "\uD83D\uDE4F",
    "wave" to "\uD83D\uDC4B",
    "point_right" to "\uD83D\uDC49",
    "point_left" to "\uD83D\uDC48",
    "eyes" to "\uD83D\uDC40",
    // Hearts / symbols
    "heart" to "\u2764\uFE0F",
    "broken_heart" to "\uD83D\uDC94",
    "fire" to "\uD83D\uDD25",
    "sparkles" to "\u2728",
    "star" to "\u2B50",
    "star2" to "\uD83C\uDF1F",
    "100" to "\uD83D\uDCAF",
    "boom" to "\uD83D\uDCA5",
    "zap" to "\u26A1",
    "tada" to "\uD83C\uDF89",
    "confetti_ball" to "\uD83C\uDF8A",
    "rocket" to "\uD83D\uDE80",
    // Status
    "white_check_mark" to "\u2705",
    "check" to "\u2714\uFE0F",
    "heavy_check_mark" to "\u2714\uFE0F",
    "x" to "\u274C",
    "negative_squared_cross_mark" to "\u274E",
    "warning" to "\u26A0\uFE0F",
    "question" to "\u2753",
    "grey_question" to "\u2754",
    "exclamation" to "\u2757",
    "grey_exclamation" to "\u2755",
    "bangbang" to "\u203C\uFE0F",
    "interrobang" to "\u2049\uFE0F",
    "no_entry" to "\u26D4",
    "stop_sign" to "\uD83D\uDED1",
    // Objects / tools
    "bulb" to "\uD83D\uDCA1",
    "book" to "\uD83D\uDCD6",
    "books" to "\uD83D\uDCDA",
    "bookmark" to "\uD83D\uDD16",
    "memo" to "\uD83D\uDCDD",
    "pencil" to "\u270F\uFE0F",
    "pencil2" to "\u270F\uFE0F",
    "hammer" to "\uD83D\uDD28",
    "wrench" to "\uD83D\uDD27",
    "gear" to "\u2699\uFE0F",
    "lock" to "\uD83D\uDD12",
    "unlock" to "\uD83D\uDD13",
    "key" to "\uD83D\uDD11",
    "package" to "\uD83D\uDCE6",
    "bug" to "\uD83D\uDC1B",
    "mag" to "\uD83D\uDD0D",
    "chart_with_upwards_trend" to "\uD83D\uDCC8",
    "chart_with_downwards_trend" to "\uD83D\uDCC9",
    "clipboard" to "\uD83D\uDCCB",
    "computer" to "\uD83D\uDCBB",
    "phone" to "\uD83D\uDCF1",
    "email" to "\uD83D\uDCE7",
    "calendar" to "\uD83D\uDCC5",
    "clock" to "\uD83D\uDD52",
    "hourglass" to "\u231B",
    "tv" to "\uD83D\uDCFA",
    "link" to "\uD83D\uDD17",
    "paperclip" to "\uD83D\uDCCE",
    // Food / nature
    "coffee" to "\u2615",
    "beer" to "\uD83C\uDF7A",
    "pizza" to "\uD83C\uDF55",
    "cake" to "\uD83C\uDF70",
    "sun" to "\u2600\uFE0F",
    "sunny" to "\u2600\uFE0F",
    "moon" to "\uD83C\uDF19",
    "cloud" to "\u2601\uFE0F",
    "umbrella" to "\u2614",
    "snowflake" to "\u2744\uFE0F",
    "cat" to "\uD83D\uDC31",
    "dog" to "\uD83D\uDC36",
    "robot" to "\uD83E\uDD16",
    "ghost" to "\uD83D\uDC7B",
    "alien" to "\uD83D\uDC7D",
    // Arrows
    "arrow_up" to "\u2B06\uFE0F",
    "arrow_down" to "\u2B07\uFE0F",
    "arrow_left" to "\u2B05\uFE0F",
    "arrow_right" to "\u27A1\uFE0F",
    "arrows_counterclockwise" to "\uD83D\uDD04",
)
